# Generated by Django 2.0.1 on 2018-01-26 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180126_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 26, 9, 14, 35, 684619, tzinfo=utc)),
        ),
    ]
