# Generated by Django 2.0.1 on 2018-02-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180207_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='begin_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
